MODEL_PATH = "models/active_model.pt"
OBJECT_MODEL_PATH = "models/yolo11n.pt"
POSE_MODEL_PATH = "models/yolo11s-pose.pt"
POSE_MODEL_ID = "yolo11s-pose.pt"
POSE_AUTO_DOWNLOAD = False
POSE_FALLBACK_MODEL_PATH = "models/yolo11n-pose.pt"

RUN_MODE = "sim"  # "real" or "sim"
SIM_VIDEO_PATH = "videos/video1.mp4"
SIM_LOOP_VIDEO = True
SIM_COMMAND_LOG_PATH = "logs/sim_commands.csv"

CONF_THRESHOLD = 0.34
FALLBACK_CONF_THRESHOLD = 0.22
FALLBACK_INFER_IMGSZ = 768
OBJECT_DETECTION_ENABLED = False
OBJECT_CONF_THRESHOLD = 0.24
OBJECT_DISPLAY_CLASSES = [
    "boat",
    "surfboard",
    "kite",
    "sports ball",
    "frisbee",
    "bottle",
]
OBJECT_MAX_RESULTS = 6
OBJECT_MIN_AREA_RATIO = 0.0012
POSE_ENABLED = True
POSE_CONF_THRESHOLD = 0.25
POSE_MIN_KEYPOINT_CONF = 0.25
POSE_INFER_EVERY_N_FRAMES = 4
POSE_DRAW_OVERLAY = True
POSE_RUN_ON_CROPS = True
POSE_BATCH_INFERENCE = True
POSE_CROP_EXPAND = 0.18
POSE_CROP_MIN_SIDE = 80
POSE_TEMPORAL_SMOOTH = 0.68
POSE_MAX_JUMP_NORM = 0.55
POSE_MAX_BONE_RATIO = 2.8
POSE_LOW_QUALITY_HOLD_FRAMES = 4

FRAME_WIDTH = 960
FRAME_HEIGHT = 720
MANUAL_SPEED = 100
REAL_RC_HZ = 80.0
REAL_RC_CMD_TIMEOUT_SEC = 0.35
REAL_RC_SLEW_STEP = 8
REAL_RC_FB_SLEW_STEP = 10
REAL_LINK_FAIL_STREAK_TRIG = 10
REAL_LINK_LOST_SEC_TRIG = 1.20
REAL_LAND_RETRY_COOLDOWN_SEC = 1.0
REAL_FAILSAFE_AUTO_LAND = True

TARGET_AREA = 85000
AUTO_TRACK_YAW_KP = 0.24
AUTO_TRACK_YAW_DEADZONE_PX = 10
AUTO_TRACK_YAW_MIN_CMD = 10
AUTO_TRACK_YAW_MAX = 55
AUTO_TRACK_FB_BAND = 0.10
AUTO_TRACK_FB_MIN_RATIO = 0.72
AUTO_TRACK_FB_MAX_RATIO = 1.32
AUTO_TRACK_FB_MAX_FWD = 32
AUTO_TRACK_FB_MAX_BWD = 32
AUTO_TRACK_FB_MIN_STEP = 8
AUTO_TRACK_WATCH_FB_BOOST = 1.20
AUTO_TRACK_ALERT_FB_BOOST = 1.42
AUTO_TRACK_WATCH_YAW_BOOST = 1.10
AUTO_TRACK_ALERT_YAW_BOOST = 1.22
AUTO_TRACK_WATCH_TARGET_AREA_SCALE = 1.08
AUTO_TRACK_ALERT_TARGET_AREA_SCALE = 1.18
AUTO_TRACK_RISE_RATE_TRIG = 0.24
AUTO_TRACK_RISE_FB_BONUS = 0.14
AUTO_TRACK_RISE_YAW_BONUS = 0.10
AUTO_TRACK_ACUTE_TRIG = 0.62
AUTO_TRACK_ACUTE_FB_BONUS = 0.12

# Risk v2 thresholds
RISK_ENTER_RESCUE = 0.72
RISK_EXIT_RESCUE = 0.55
RISK_WINDOW = 20
RISK_WARMUP_FRAMES = 4
RISK_MAX_MATCH_DIST = 140

# Risk persistence (anti-flicker)
RISK_WATCH_ENTER = 0.42
RISK_WATCH_EXIT = 0.32
RISK_ALERT_ENTER = 0.64
RISK_ALERT_EXIT = 0.52
RISK_WATCH_ENTER_SECONDS = 0.7
RISK_ALERT_ENTER_SECONDS = 1.2
RISK_EXIT_SECONDS = 1.2

# Fast distress path (for early drowning suspicion)
RISK_FAST_WATCH = 0.50
RISK_FAST_ALERT = 0.68
RISK_FAST_WATCH_SECONDS = 0.35
RISK_FAST_ALERT_SECONDS = 0.25
RISK_FAST_WATCH_ACUTE = 0.56
RISK_FAST_ALERT_ACUTE = 0.70
RISK_MIN_RAW_FOR_ALERT = 0.60

# Fast rise path (response-time optimization)
RISK_RISE_WATCH_RATE = 0.14
RISK_RISE_ALERT_RATE = 0.22
RISK_RISE_WATCH_SECONDS = 0.22
RISK_RISE_ALERT_SECONDS = 0.20
RISK_RISE_WATCH_ACUTE = 0.48
RISK_RISE_ALERT_ACUTE = 0.58

# Rescue transition shaping (state machine)
RISK_RESCUE_ALERT_ENTER = 0.64
RISK_RESCUE_WATCH_ENTER = 0.68
RISK_RESCUE_RISE_RATE_TRIG = 0.24
RISK_RESCUE_RISE_DROP = 0.08
RISK_RESCUE_ACUTE_TRIG = 0.62
RISK_RESCUE_ACUTE_DROP = 0.06

# Operator policy (UX/operations)
ACTION_SAFE = "MONITOR"
ACTION_WATCH = "APPROACH + OBSERVE"
ACTION_ALERT = "RESCUE NOW"

# Benchmark defaults
BENCHMARK_LABELS_PATH = "benchmarks/labels.json"
BENCHMARK_OUTPUT_DIR = "logs"
BENCHMARK_ALERT_STATE = "ALERT"
BENCHMARK_RESIZE = True

# Runtime performance tuning
BATTERY_POLL_INTERVAL_SEC = 1.0
SAFETY_BATTERY_CHECK_INTERVAL_SEC = 1.0
REAL_STREAM_STALE_SEC = 0.50
REAL_STREAM_RESET_COOLDOWN_SEC = 2.0

# Water-region gating for sea/drowning scenarios.
WATER_FILTER_ENABLED = False
WATER_LINE_RATIO = 0.55

IGNORE_CLASSES = [
    "surfboard",
    "boat",
    "kite",
    "bird",
    "dog",
    "chair"
]
